alias python=/usr/local/bin/python3.7
alias sublime='open /Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl'
alias music="open ~/Music"
alias speedtest-ctl='/Applications/speedtest-cli/speedtest'
alias chrome='open -a "google chrome"'
alias cd-g='cd ~/Documents/GitHub'
alias changesh='open /bin/bash'
alias cd-tab='cd ~/Documents/Winnie/.tab'
alias 想='ls 想'
# export PS1='\u@\h:\[\e[33m\]\w\[\e[0m\]\$ '
export EDITOR='vim'
